### ISSUE TITLE
Creation de la documentation

### ISSUE THREAD

**Issue by pnavaro** [jeremyomer/KidneyExchange.jl#1]
Salut Jeremy
J'ai ajouté les premiers fichiers pour la doc. Il reste à entrer les clés pour générer le site. Je ne peux pas le faire car je ne suis pas propriétaire du dépôt. Voici les instructions

```
KidneyExchange.jl (master)$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.1 (2021-12-22)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.7) pkg> add DocumenterTools
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`

julia> using DocumenterTools

(@v1.7) pkg> activate .
  Activating project at `~/JuliaProjects/KidneyExchange.jl`

julia> using KidneyExchange
julia> DocumenterTools.genkeys(KidneyExchange)
```
Il te reste à suivre la procédure qui s'affiche en sortie de la dernière commande

A bientôt

PS: Il y a encore un souci avec le nom du package qui s'appelle toujours KEP par endroit, il faudrait remplacer par KidneyExchange

**Comment by pnavaro** [comment]
Salut Jeremy il faut recommencer la procédure en haut de cette issue, je ne comprends pas trop pourquoi mais c'est ce qui est conseillé

```
Please make sure you have the correct access rights
and the repository exists.
┌ Error: Git failed to fetch git@github.com:jeremyomer/KidneyExchange.jl
│ This can be caused by a DOCUMENTER_KEY variable that is not correctly set up.
│ Make sure that the environment variable is properly set up as a Base64-encoded string
│ of the SSH private key. You may need to re-generate the keys with DocumenterTools.
```

**Comment by jeremyomer** [comment]
Je pense avoir fait le nécessaire. Ce n'est pas la première fois que j'ai des problèmes avec Github ces derniers temps. Ils font des changements sans cesse, ce qui casse parfois des choses qui fonctionnaient très bien jusqu'ici. 
Est-ce qu'il y a une commande à lancer pour que la doc se mette à jour (en espérant que la manip ait fonctionné) ?

**Comment by pnavaro** [comment]
Récemment ils ont eu un problème de sécurité et il a fallu renouveler toutes les clés ssh.

**Comment by pnavaro** [comment]
Pour la doc c'est bon !

 https://jeremyomer.github.io/KidneyExchange.jl/dev/

**Comment by jeremyomer** [comment]
Je viens de voir ça, merci !

**Comment by pnavaro** [comment]
Je ferme le ticket, ca marche, désolé pour les tonnes d'emails qui a du recevoir. Bonne soirée!

**Comment by jeremyomer** [comment]
Vue la vitesse à laquelle tu m'as aidé, je vais quand-même pas me plaindre pour une petite dizaine d'emails qui sont allés direct à la poubelle. Encore merci à toi !
