### ISSUE TITLE
Error when running KEPTestBP.jl on Preflib instance with altruistic donor

### ISSUE THREAD

**Issue by WPettersson** [jeremyomer/KidneyExchange.jl#20]
Me again :)

Assuming that .wmd/.dat file loading from the branch 16-file-format-description-seems-off is incorporated, I am getting the following error when running julia ../../KEPTestBP.jl 00036-00000011 3 2

```
 vertex coverage: [1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 2]
- by chain: [17, 1, 17]
ERROR: LoadError: A vertex is covered more than once in the solution
```

Note that this is preflib instance 00036-00000011 - it has one altruistic donor, and this seems to be causing the issue.

I cannot for sure say whether this is related to #16 or not, as it might be that file reading is not right for altruistic donors isn't right still, or it may be something else in the code.

**Comment by pnavaro** [comment]
Sorry but this is holiday for me this week ❄️❄️❄️. I take a look next Monday 

Cheers 
Pierre

**Comment by pnavaro** [comment]
Sorry for the delay, I think I fixed this error. When I read the wmd file with new format the matrix containing weights was not filled well.  This is definitely linked whith #17
